x-common-settings: &common-settings
  build: .
  env_file: .env
  restart: on-failure
  environment:
    - STORAGE_DIR=/clerk_sites
    - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=${OTEL_EXPORTER_OTLP_TRACES_ENDPOINT:-http://victoria-traces:10428/insert/opentelemetry/v1/traces}
    - OTEL_SERVICE_NAME=clerk
    - METRICS_PORT=0
    - PROMETHEUS_MULTIPROC_DIR=/prom
  volumes:
    - ${STORAGE_DIR}:/clerk_sites/
    - .:/app
    - prom-multiproc:/prom
  networks:
    - clerk

services:
  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
    networks:
      - clerk

  fetch_worker:
    <<: *common-settings
    command: clerk worker fetch -n ${FETCH_WORKERS}
    pid: "host"

  ocr_worker:
    <<: *common-settings
    command: clerk worker ocr -n ${OCR_WORKERS}
    pid: "host"

  compilation_worker:
    <<: *common-settings
    command: clerk worker compilation -n ${COMPILATION_WORKERS}
    pid: "host"

  deploy_worker:
    <<: *common-settings
    command: clerk worker deploy -n ${DEPLOY_WORKERS}
    pid: "host"

  metrics:
    <<: *common-settings
    command: clerk metrics-exporter
    pid: "host"
    environment:
      - STORAGE_DIR=/clerk_sites
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=${OTEL_EXPORTER_OTLP_TRACES_ENDPOINT:-http://victoria-traces:10428/insert/opentelemetry/v1/traces}
      - OTEL_SERVICE_NAME=clerk
      - METRICS_PORT=9800
      - PROMETHEUS_MULTIPROC_DIR=/prom
    ports:
      - "9800:9800"

networks:
  clerk:

volumes:
  prom-multiproc:
