"""add queue tables

Revision ID: c27bd77144ce
Revises: 45db71312424
Create Date: 2026-01-06 21:35:39.233197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c27bd77144ce'
down_revision: Union[str, Sequence[str], None] = '45db71312424'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_tracking',
    sa.Column('rq_job_id', sa.String(), nullable=False),
    sa.Column('site_id', sa.String(), nullable=False),
    sa.Column('job_type', sa.String(), nullable=False),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('rq_job_id')
    )
    op.create_index(op.f('ix_job_tracking_site_id'), 'job_tracking', ['site_id'], unique=False)
    op.create_table('site_progress',
    sa.Column('site_id', sa.String(), nullable=False),
    sa.Column('current_stage', sa.String(), nullable=True),
    sa.Column('stage_total', sa.Integer(), server_default='0', nullable=True),
    sa.Column('stage_completed', sa.Integer(), server_default='0', nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('site_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site_progress')
    op.drop_index(op.f('ix_job_tracking_site_id'), table_name='job_tracking')
    op.drop_table('job_tracking')
    # ### end Alembic commands ###
